# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-eslint.git
    rev: a83e0a62fd6b81c958ef40d354e4d8938604c9ea
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@6.6.0
          - eslint-plugin-import@2.18.2
